FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Unofficial BMW ConnectedDriveAPI

Work in progress reverse engineered API for BMW Connected Drive, presented as-is with no implied warranty
or license, a ruby implementation of the API can be found at - https://github.com/jacktams/ConnectedDriveAPI